language: node_js
sudo: false
node_js:
  - '4.1'

cache:
  directories:
    - node_modules

before_install:
  - npm install -g typescript@1.6.2
  - npm install -g tsd@next

install:
  # Disable the spinner, it looks bad on Travis
  - npm config set spin false
  # Install dependencies
  - npm install
  - tsd reinstall

script:
  - gulp ci