language: node_js
sudo: false
node_js:
  - '4.1'

cache:
  directories:
    - node_modules

install:
  # Disable the spinner, it looks bad on Travis
  - npm config set spin false
  # Install npm dependencies
  - npm install